



export const firstTimeLogin = async () => {
    try {
        
        
    } catch (error) {
      console.error(error)  
    }
}